version: '2.2'

services:
  apt-cacher-ng:
    restart: always
    image: mathiasstadler/apt-cacher-ng-yum:latest
    init: true
    ports:
    - "3142:3142"
    volumes:
    - /srv/docker/apt-cacher-ng:/var/cache/apt-cacher-ng
    - ./acng.conf:/etc/apt-cacher-ng/acng.conf
